apiVersion: v1
kind: Deployment
metadata:
  name: next_app
spec:
  containers:
  - name: next_app
    image: dillax/next_app:f96a906f07222a952891becce2605233331a9d39
    ports:
    - containerPort: 3000
